theopensystemslab/atlas-ownership-next

- components/Footer.tsx
- components/GlobeEntry.tsx
- styles/globals.css
Markers are just defaulted back to pin - we can address this when we look at clusters.
> feat: Popover

- components/Chart.tsx
renders an interactive chart when `rollupToPatternClass={false}`
this adds basic interactivity that we can continue to cleanup/style and add content to:
- hover state (opacity of bar color only for now, should maybe add cursor pointer style too)
- on click, render a container below the chart to show this pattern's description
- Figma shows accordion drawer _overwriting_ original bar on open but I've made decision to display below for now both for simplicity and so that you can continue to see strength score/comparison (since strenght # is never mentioned in content)
> feat: basic chart interactivity

- components/Header.tsx
- components/sidebar/PatternClassAccordion.module.css
- components/sidebar/PatternClassAccordion.tsx
- components/sidebar/PatternClassAccordionPattern.module.css
- components/sidebar/PatternClassAccordionPattern.tsx
- components/sidebar/Sidebar.module.css
- components/sidebar/Sidebar.tsx
- lib/queries.ts
- lib/store.ts
- lib/types.ts
- styles/globals.css
Still to do...
- Tidy up animations / transitions
- Overflow Y for the sidebar. Spent a bit of time on this with no luck. `overflow-y-auto` on the sidebar solves our scrolling problem but this makes the chevron disappear. I'll come back to this 👌 
Ignored for now...
- Empty "Use" category - this should be populated shortly by Niamh
> feat: Sidebar styling

- components/Chart.tsx
- components/layout/EntryLayout.tsx
- lib/types.ts
From Ollie on Slack - 
> just doing a quick bit of content stuff--are we able to get line breaks in the descriptions? eg in [Andelsbolig page](https://gorgeous-concha-ffb906.netlify.app/entry/andelsbolig), line breaks are shown in Sanity before and after "Legal Context" and "Historical Context" but not in the frontend, tried break tags too but it just shows the tags as text...
> fix: Render line breaks on Entry page

- components/map/Markers.tsx
Marker (seen in Portugal) now matches style of clusters and Figma 👌
> fix: Custom marker style

- components/Chart.tsx
- components/layout/EntryLayout.tsx
this file was getting a little gnarly
now tidier and updated with:
- consistent flex grid styles used for bar chart sizing _and_ PatternsLayout page now
- better type interfaces
- no more unused tailwind classes
looking pretty good i think! 
still outstanding but hopefully much easier with new code structure (anyone please feel free to pick up!):
> fix: better charts

- components/PageNavbar.tsx
- components/carousel/Carousel.tsx
- components/layout/EntryLayout.tsx
- components/layout/NoopLayout.tsx
- components/layout/PatternsLayout.tsx
- pages/entry/[slug].tsx
A few things missed whilst merging / rebasing - 
- `carouselItems` are now passed into `EntryLayout` to display items at bottom of page
- "Explore the patterns" page now has the standard header
- Another (maybe better, but more complex) would have been a refactor of `NoopLayout` to account for different colour pages. Happy to have a crack at this time allowing.
> fix: Entry Carousel & Explore Patterns navbar

- components/Chart.tsx
- components/layout/EntryLayout.tsx
- lib/types.ts
was noticing that some of "rolled up to pattern class" charts were not matching the charts "by terms"
see example:
- https://deploy-preview-58--gorgeous-concha-ffb906.netlify.app/entry/freehold-in-alentejo
chart math now corrected & simplified to reference `term.strength` which is consistently populated I think rather than the old `rightsIntensity` & `obligationsIntensity`
also added a little local feature-flag-esque toggle `DEBUG_CHART` which we can manually set from entry page to display a simple radio button to easily toggle between chart variations - otherwise it's a little clumsy to compare the map markers to the entry page.
> fix: correct chart math using term "strength"

- components/Chart.tsx
to be better aligned with figma! will need to swap with "real" icons once ready
> feat: add placeholder icons to chart

- components/Chart.tsx
a term has: 
- description = how it applies to the given entry
- pattern.description = how the pattern is defined
realized we were leaving out the first description entirely! 
not really in figma, so made up a design myself for now - feedback welcome:
> feat: when expanding a chart row, show term definition and its' unique description for this entry

- components/Chart.tsx
- components/map/Markers.tsx
- styles/globals.css
- tailwind.config.js
**What's going on here?**
- Each row of the chart is now 8 fractions wide
- Up to 5 columns are used for the values, the remainder for the labels
- To make things align, we always make sure that the entire 8 columns are used 
TODO: 
- Implement this on "rolled up" chart
> feat: Align labels with bars

- components/layout/EntryLayout.tsx
- components/map/Markers.tsx
Fixes https://www.notion.so/opensystemslab/The-Atlas-of-Ownership-176a5620cdfd4465aacb20562bfe64f7?p=8db264992a8d44ba8a02b49f41259ec7&pm=s
The above bug refers to "Social Renting - Secure Council Tenancy Norwich" which I can't locate on Sanity or on the map - I've asked Niamh about this to see if there's an underlying issue.
It's displayed here on the live preview - https://gorgeous-concha-ffb906.netlify.app/entry/social-renting-secure-council-tenancy
> fix: Hide chart if entry has no terms

- components/Header.tsx
To test - 
- I can now interact with the globe behind the header
- I can still click "Why?", and search / filter buttons
> fix: Don't block globe interactivity with header

- components/Chart.tsx
- components/layout/PatternsLayout.tsx
- components/layout/ui/PatternIcon.tsx
- components/sidebar/Sidebar.tsx
- lib/queries.ts
- lib/types.ts
- next.config.js
I've uploaded a random Carbon icon to the "Variable rents" pattern on Sanity to test this - https://osl.sanity.studio/desk/pattern;863dedd7-07f2-4950-90af-692880bef23f
**Chart icons**
**Sidebar icons**
**Pattern icons**
> feat: Custom icons

- components/ContentPage.tsx
- lib/page.tsx
- lib/queries.ts
- lib/types.ts
- pages/about.tsx
- pages/licence.tsx
- pages/terms-of-use.tsx
- server/routers/_app.ts
|Sanity|Atlas|
|---|---|
|![image](https://user-images.githubusercontent.com/20502206/214691640-485bcd6e-8a9b-4d9a-ad18-b10d8ed6032f.png)|![image](https://user-images.githubusercontent.com/20502206/214691151-4487547b-613d-4b5f-ab48-2b7e46d2fc4d.png)|
I'm using Sanity "Block Content" component to allow rich text to be displayed, and currently just styling `p` and `blockquote` tags using `react-portabletext` (https://github.com/portabletext/react-portabletext)
Looks pretty straightforward - as we get a bit more guidance on styling these pages we can add custom styles and components.
> feat: Get page content from Sanity

- components/Chart.tsx
**Principles**
- If a term has a zero value, do not give it a colour. This means they're visually easy to spot on charts
- If a term has a zero value, still give it the spacing of a "1" value. This keeps the layout consistent.
Hopefully once all terms have a strength, we can remove this logic and enforce this at the Sanity level, but hopefully this works for now!
> fix: Chart zero values

- components/ContentPage.tsx
- components/layout/PatternsLayout.tsx
There should be no visual changes here, just where the content is coming from.
|**Before**|**After**|
|---|---|
|![image](https://user-images.githubusercontent.com/20502206/215075131-239f5222-179b-4bcb-b97a-a7f03a7f7305.png)|![image](https://user-images.githubusercontent.com/20502206/215075095-60a90350-5ff3-4f78-9a82-f5f8c4d9cd4e.png)|
> feat: Read explore patterns content from Sanity

- components/layout/EntryLayout.tsx
https://www.notion.so/opensystemslab/The-Atlas-of-Ownership-176a5620cdfd4465aacb20562bfe64f7?p=b2e8ed39a45b4dbc84b8f8f2b4ad335e&pm=s
> fix: Stop entry pages 'stacking' on top of each other

- components/sidebar/Sidebar.tsx
https://www.notion.so/opensystemslab/Remove-second-circle-thing-from-sidebar-tab-2071d7d64095459e9644729ae0488986
> fix: Tuck 'all entries' into sidebar

- components/Header.tsx
https://www.notion.so/opensystemslab/Remove-second-circle-thing-from-sidebar-tab-2071d7d64095459e9644729ae0488986
> fix: Why -> About

- components/ContentPage.tsx
- components/Header.module.css
- components/Header.tsx
- styles/globals.css
Making the header wider than the content doesn't always guarantee one will actually be wider. Based on how important this is we can always increase the different between the header at 40% and text at 33%.
Colours purely indicative!
> fix: Standard title style across pages

- components/Chart.tsx
So this fixes a bug described here were all pattens show as Obligations - https://www.notion.so/opensystemslab/The-Atlas-of-Ownership-176a5620cdfd4465aacb20562bfe64f7?p=e4216dd381914c1e8236b9910659f0fe&pm=s
This fixes the issue of the term being `undefined` and defaulting to an Obligation, but leaves a few open questions...
- Are there still many patterns without a `type` populated? (So we need a fallback based on `intensity`)
- What was our thinking behind having "Rights", "Obligations" and "Limitations" - was it just a semantic thing that we didn't tidy up?
**Fixed example on PR** - https://deploy-preview-113--gorgeous-concha-ffb906.netlify.app/entry/st-nicholas-abbey-tenants-contract
**Same example on `main`** - https://gorgeous-concha-ffb906.netlify.app/entry/st-nicholas-abbey-tenants- …
> fix: _id typo, handle "Limitation" types
