theopensystemslab/atlas-ownership-next

pages/entry/[slug].tsx
tailwind.config.js

chore: Add AoO colours to Tailwind

---

components/GlobeChildren.tsx
components/GlobeEntry.tsx
components/GlobeLayout.tsx
components/layout/EntryLayout.tsx
lib/queries.ts
lib/types.ts
package-lock.json
package.json
pages/entry/[slug].tsx
styles/globals.css
yarn.lock

feat: Rough entry skeleton

---

components/layout/EntryLayout.tsx
lib/types.ts

feat: Display entry.tenureType

---

pages/about.tsx

feat: about page skeleton

---

components/GlobeEntry.tsx
components/layout/EntryLayout.tsx
components/layout/PatternsLayout.tsx
lib/queries.ts
lib/types.ts
package-lock.json
package.json
pages/api/trpc/[trpc].ts
pages/entry/[slug].tsx
pages/patterns.tsx
styles/globals.css
tailwind.config.js
yarn.lock

feat: Explore Patterns page

---

components/layout/EntryLayout.tsx
lib/types.ts

wip: update entry page layout per figma

---

components/layout/PatternsLayout.tsx

fix: Add extra column for access

---

components/layout/EntryLayout.tsx
components/layout/ui/Tag.tsx
lib/types.ts

I couldn't find any entries with a tags so I added some to an example entry, then deleted them, to test this.

feat: Entry tags

---

components/sidebar/PatternClassAccordion.tsx

feat: Add description to sidebar

---

components/map/Markers.tsx

I think this got lost in a merge conflict somewhere

fix: Popover find out more style

---

components/layout/NoopLayout.tsx
pages/about.tsx
pages/licence.tsx
pages/terms-of-use.tsx

so the footer links go somewhere! plus updating the layout for static pages to share a unique nav bar
content TBD!

feat: add placeholder license & terms-of-use pages

---

components/layout/PatternsLayout.tsx

add back button to patterns page

---

components/layout/EntryLayout.tsx

context https://opensystemslab.slack.com/archives/C02BKC5QZ8E/p1674203946888039
airtable public form: https://airtable.com/shrl7X5UhiOHUaj3r
airtable base (OSL workspace): https://airtable.com/appMZX84pkCZiD6YU/tblTeNLfsalMpu34l/viwErv5HyKzphKQ90?blocks=hide

chore: link airtable form to suggest an improvement to an entry

---

components/Chart.tsx

feat: Add up chevron to expandable row

---

components/sidebar/Accordion.tsx
components/sidebar/AccordionItem.module.css
components/sidebar/AccordionItem.tsx
components/sidebar/Sidebar.tsx
components/sidebar/selection.ts
lib/types.ts

I'll branch off this to wire them up just to keep things and small, simple, and separate as possible

feat: Add Entry Type & Tenure Type accordions to sidebar

---

components/map/MapboxGlobe.tsx
components/sidebar/Sidebar.tsx
components/sidebar/selection.ts

feat: Wire up TenureType and EntryType filters

---

components/layout/EntryLayout.tsx
components/layout/ui/Tag.tsx

fix: Fix tag style

---

components/Footer.tsx
lib/queries.ts
server/routers/_app.ts

Also a few tidy ups here with spacing and actually wiring up the logos.

feat: Add contributors to footer

---

components/Header.tsx
components/sidebar/Sidebar.module.css
components/sidebar/Sidebar.tsx
components/sidebar/selection.ts

https://user-images.githubusercontent.com/20502206/214825644-72c8942a-185f-4a90-a2a3-e684ce5f0296.mov

feat: Add reset functionality to sidebar

---

components/layout/PatternsLayout.tsx

**Large**
**Medium**
**Small**
**Below Small**

feat: Mobile patterns layout

---

components/Chart.tsx
lib/queries.ts

feat: Add legal mechanisms to chart

---

components/layout/ui/PatternIcon.tsx

chore: Update fallback icon

---

components/Chart.tsx

sometimes the wrong bar was opening on click - this should feel smoother now and cover all scenarios!

fix: tweak open/close interactions on bars

---

components/Chart.tsx
components/layout/EntryLayout.tsx

https://www.notion.so/opensystemslab/The-Atlas-of-Ownership-176a5620cdfd4465aacb20562bfe64f7?p=c2d99f7cdbc54cc6803b54af6865ba3b&pm=s

fix: Increase entry spacing

---

components/Footer.module.css
components/Footer.tsx
components/layout/GlobeLayout.module.css
components/layout/GlobeLayout.tsx
components/map/MapboxGlobe.tsx
components/sidebar/Sidebar.module.css
pages/_document.tsx
styles/globals.css

This ended up being more work than expected...!
Footer bg-colour in video is just an indication of breakpoints
https://user-images.githubusercontent.com/20502206/215540377-776ce10b-858d-4c5d-aada-1f88af9cc0a0.mov

feat: Responsive footer layout

---

components/Header.module.css
components/Header.tsx
styles/globals.css

https://www.notion.so/opensystemslab/The-Atlas-of-Ownership-176a5620cdfd4465aacb20562bfe64f7?p=eb5f9aa8fb5d42a0bd3dfe6b212a97ab&pm=s

fix: Match header style to figma

---

components/Footer.module.css
components/layout/GlobeLayout.tsx

Something I missed with commit [10b4956](https://github.com/theopensystemslab/atlas-ownership-next/pull/93/commits/10b49562c42bb3bbc15ca4cf48dd0f4fb8f2bfdb)

fix: Entry sidebar overflow-x

---

components/Header.module.css
components/Header.tsx
components/Search.module.css

|Site|Figma|
|---|---|
|<img width="697" alt="image" src="https://user-images.githubusercontent.com/20502206/215591656-f5ef3adb-b0fa-466c-9afa-74d7efe5923e.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/20502206/215591484-40557f85-8cfa-4dd3-92a4-b59daef51e6e.png">|

feat: Add header links

---

components/map/Markers.tsx
components/sidebar/Sidebar.tsx
lib/entry.ts
lib/types.ts

https://www.notion.so/opensystemslab/The-Atlas-of-Ownership-176a5620cdfd4465aacb20562bfe64f7?p=5a0dac75b9884b27b56e24df2e0dda8d&pm=s

fix: consistently format tenure types

---

components/Header.tsx
components/Search.module.css
components/Search.tsx

https://www.notion.so/opensystemslab/The-Atlas-of-Ownership-176a5620cdfd4465aacb20562bfe64f7?p=80897b0308e3440e88f6e14d04e35a42&pm=s

feat: Collapse search on mobile

---

components/ContentPage.tsx
components/layout/PatternsLayout.tsx

https://opensystemslab.slack.com/archives/C02BKC5QZ8E/p1675291389489529

fix: Font size tweaks
